spring:
  application:
    name: outbox-worker
  config:
    import: classpath:outbox.yml
server:
  port: ${WORKER_PORT:8081}
management:
  endpoints:
    web:
      exposure:
        include: health,info
